spring:
  data:
    mongodb:
      database: ExamType
      host: localhost
      port: 27017
  application:
    name: Exam-Service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.uuid}
  main:
    allow-bean-definition-overriding: true

server:
  port: 8001

management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /ui
  api-docs:
    path: /api-docs