spring:
  data:
    mongodb:
      database: ExamType
      host: localhost
      port: 27017
  application:
    name: Exam-Service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.uuid}
  main:
    allow-bean-definition-overriding: true

server:
  port: 8001

management:
  security:
    enabled: false
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      authService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      authService:
        maxRetryAttempts: 5
        waitDuration: 10s


springdoc:
  swagger-ui:
    path: /ui
  api-docs:
    path: /api-docs